---
- name: install and setup mysql db
  hosts: mysql_server
  become: yes
  tasks:
    - name: include vars
      include_vars: vars/db

    - name: copy db data to remote location
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql
      tags:
        - deploy

    - name: import db backup
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: "{{dbuser}}"
        login_password: "{{dbpass}}"
        name: "{{dbname}}"
        state: import
        target: /tmp/db_backup.sql
      notify:
        - restart mysql
      tags:
        - deploy

  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
