---
- name: install and start rabbitmq server
  hosts: amq_server
  become: yes
  tasks:
    - name: install erlang repository
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

    - name: erlang solution public key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
        state: present

    - name: install erlang
      apt:
        name: erlang
        state: present
        update_cache: yes
        cache_valid_time: 86400

    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
        state: present

    - name: install rabbitmq repository
      apt_repository:
        repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
        state: present

    - name: Install Rabbit rmq
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes

    - name: Start & Enable rmq
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Config setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - restart rmq

    - name: create rmq user
      rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - restart rmq

    - name: enable the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rmq

  handlers:
    - name: restart rmq
      service:
        name: rabbitmq-server
        state: restarted
